name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.0

      - name: Install cogit
        run: |
          sudo ./install.sh
          if [[ $? -ne 0 ]]; then
            echo "Failed when installing cogit"
            exit 1
          fi
